Handle missing clip_fea
Avoids
```
clip_fea     = RegContext.get_clip_fea().to(x.dtype)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'to'
```